name: Docs

# Docs build and publishes the Vuepress documentation website.
# This workflow is run on every pull request and push on main.
# The deployment of the docs is made only on each push on main.
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  Markdown-Link-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
        with:
          use-quit-mode: "yes"
          folder-path: "doc"

  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node 🧰
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Build 🔧
        run: |
          npm install
          npm ci
          npm run docs:build

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/.vuepress/dist
